export const PATH = {
  DANG_KY: "/dang-ky",
  TRANG_CHU: "/",
  THONG_TIN_CA_NHAN: "/thong-tin-ca-nhan",
  DOI_MAT_KHAU: "/doi-mat-khau",
  DANG_NHAP: "/dang-nhap",
  CHI_TIET_SAN_PHAM: "/san-pham/chi-tiet",
  SAN_PHAM: "/san-pham",
  GIO_HANG: "/gio-hang",
  THANH_TOAN: "/thanh-toan",
  LICH_SU_MUA_HANG: "/lich-su-mua-hang",
  MA_GIAM_GIA_CUA_TOI: "/ma-giam-gia-cua-toi",
  MA_GIAM_GIA: "/ma-giam-gia",
  TIN_TUC: "/tin-tuc",
  SAN_PHAM_THEO_LOAI: "/san-pham-theo-loai",
  QUEN_MAT_KHAU: "/quen-mat-khau",
  LAM_MOI_MAT_KHAU: "/lam-moi-mat-khau",
  GIOI_THIEU: "/gioi-thieu",
  LIEN_HE: "/lien-he",
  TU_VAN: "/tu-van",
  CHUYEN_MUC_SUC_KHOE: "/chuyen-muc-suc-khoe",
};
